#version: '3.3'
#services:
  #db:
  #  container_name: request
  #  restart: always
   # environment:
   #   - POSTGRES_DB_USER=postgres
   #   -POSRTGRES_DB_PASSWORD=postgres
   #   - POSTGRES_DB_DATABASE=my
   #   - PGDATA=/var/lib/postgresql/data/pgdata
   # ports:
   #   - 5432:5432


 # app:
  #  build: .​
  #  depends_on:
  #    -db
  #  ports:
  #  - "8080:8080"
   # restart: always



    version: '3.7'

    services:

      db:
        build: './database'
        container_name: request
        restart: always
        #    volumes:
        #      - request_db:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB_USER=postgres
          - POSTGRES_DB_PASSWORD=postgres
          - POSTGRES_DB_DATABASE=my-db
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=my-db
          - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
          - 5432:5432
      #volumes:
      #  request_db:

      app:
        build: .
        ports:
          - 8080:8080
        depends_on:
          - db